# Introduction to Python Numpy Matrixes (Arrays)

In [1]:
import numpy as np

x = np.random.rand(3,4)
print x

[[0.08370684 0.22201561 0.27624279 0.28142322]
 [0.19394416 0.00761761 0.76047703 0.34014556]
 [0.69628585 0.3894016  0.97433976 0.25586864]]


In [2]:
x *= 100
print x

[[ 8.37068355 22.20156104 27.62427927 28.14232246]
 [19.39441637  0.76176126 76.04770306 34.01455638]
 [69.62858546 38.94016004 97.43397579 25.58686421]]


In [3]:
x = x.astype(int)
print x

[[ 8 22 27 28]
 [19  0 76 34]
 [69 38 97 25]]


In [13]:
print x[:,0]

[ 8 19 69]


In [14]:
print x[1,:]

[19  0 76 34]


In [15]:
y = x[0:2,:]
print y

[[ 8 22 27 28]
 [19  0 76 34]]


In [9]:
z = x[1:4,2:4]
print z

[[76 34]
 [97 25]]
