# Introduction to Python Numpy Matrices (Arrays)

- Create a matrix size 3,4 with random numbers

In [1]:
import numpy as np

x = np.random.rand(3,4)
print x

[[0.52410167 0.70960525 0.9159794  0.19009829]
 [0.25228271 0.35244069 0.44179071 0.14624133]
 [0.34318593 0.34856914 0.57149289 0.03293288]]


- Make it range from 0 to 100

In [2]:
x = (x*100).astype(int)
print x

[[52 70 91 19]
 [25 35 44 14]
 [34 34 57  3]]


- Display the first column and the first two lines

In [3]:
print x[:,0]
print x[0:2,:]

[52 25 34]
[[52 70 91 19]
 [25 35 44 14]]


- Display the last 2x2 sub matrix

In [4]:
z = x[-2:,-2:]
print z

[[44 14]
 [57  3]]
